<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="" name="pytest" skipped="3" tests="14" time="0.071" timestamp="2020-02-25T17:00:28.408877"><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="24" name="test_ZeroDivisionError[1-2]" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="24" name="test_ZeroDivisionError[19-0]" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="24" name="test_ZeroDivisionError[0-5]" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="24" name="test_ZeroDivisionError[34-3]" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="35" name="test_email_exception" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="41" name="test_IndexError" time="0.000"><skipped message="" type="pytest.xfail"></skipped></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="48" name="test_number" time="0.000"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="54" name="test_calling_undefined_fun" time="0.001"><skipped message="[NOTRUN] " type="pytest.xfail"></skipped></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="60" name="test_UnboundLocalError[12.0-11111111111111111111111111111111111111111111111]" time="0.001"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="71" name="test_RuntimeError" time="0.000"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="76" name="test_nonExitedElement" time="0.000"><skipped message="unconditional skip" type="pytest.skip">test_TestCasesList.py:77: unconditional skip</skipped></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="82" name="test_KeyError" time="0.000"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="88" name="test_OSError" time="0.000"></testcase><testcase classname="test_TestCasesList.TestCases" file="test_TestCasesList.py" line="93" name="test_OverflowError" time="0.000"></testcase></testsuite></testsuites>
